checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableNetwork: true

httpTimeout: 60000

ignorePath: true

networkConcurrency: 200

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmAlwaysAuth: true
